version: '3'

services:
  mysqlsrv:
    image: mysql:8.0.25
    environment:
      MYSQL_ROOT_PASSWORD: "MySql2019!"
      MYSQL_DATABASE: "mentoria"
    ports:
      - "3306:3306"
    networks:
      - mysql-compose-network

  adminer:
    image: adminer
    ports:
      - 8081:8080
    networks:
      - mysql-compose-network

networks:
  mysql-compose-network:
    driver: bridge